[workspace]
name = "my_isaac_train"
authors = ["carp-x <liyuxin_2016@163.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]
version = "0.0.0"

[dependencies]
python = "3.11.*"
pip = ">=23.0"
pytorch = ">=2.4.0"

lxml = ">=4.9.2, <5.0.0"
starlette = ">=0.40.0, <0.46.0"

[pypi-dependencies]
usd-core = ">=25.2.post1, <26.0"

[activation]
scripts = ["development/pixi/activation.sh"]

[tasks]
# train
train = "python scripts/reinforcement_learning/rsl_rl/train.py --task Isaac-Velocity-Rough-Anymal-C-v0 --num_envs 2048 --headless"
train_debug = "python scripts/reinforcement_learning/rsl_rl/train.py --task Isaac-Velocity-Rough-Anymal-C-v0 --num_envs 128 --headless"
# play
play = "python scripts/reinforcement_learning/rsl_rl/play.py --task Isaac-Velocity-Rough-Anymal-C-v0 --num_envs 1"
# monitor
monitor = "tensorboard --logdir=logs/rsl_rl/anymal_c_rough"

# my train rough
my_train = "python scripts/reinforcement_learning/rsl_rl/train.py --task My-Velocity-Rough-Anymal-C-v0 --num_envs 2048 --headless"
my_train_debug = "python scripts/reinforcement_learning/rsl_rl/train.py --task My-Velocity-Rough-Anymal-C-v0 --num_envs 128 --headless"
# play
my_play = "python scripts/reinforcement_learning/rsl_rl/play.py --task My-Velocity-Rough-Anymal-C-v0 --num_envs 1"
# monitor
my_monitor = "tensorboard --logdir=logs/rsl_rl/my_anymal_c_rough"

# my train flat
my_train_flat = "python scripts/reinforcement_learning/rsl_rl/train.py --task My-Velocity-Flat-Anymal-C-v0 --num_envs 2048 --headless"
my_train_flat_debug = "python scripts/reinforcement_learning/rsl_rl/train.py --task My-Velocity-Flat-Anymal-C-v0 --num_envs 128 --headless"
# play
my_play_flat = "python scripts/reinforcement_learning/rsl_rl/play.py --task My-Velocity-Flat-Anymal-C-v0 --num_envs 1"
# monitor
my_monitor_flat = "tensorboard --logdir=logs/rsl_rl/my_anymal_c_flat"
